# Generated by Django 4.2 on 2024-05-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shipping_address',
            field=models.TextField(blank=True, null=True, verbose_name=' shipping address'),
        ),
    ]
