# Generated by Django 4.2 on 2024-05-25 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='carts',
        ),
    ]
