# Generated by Django 4.2 on 2024-06-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_cartitem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='total',
            field=models.FloatField(default='0', max_length=10),
        ),
    ]
