# Generated by Django 4.2 on 2024-06-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_percent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
