# Generated by Django 4.2 on 2024-06-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_alter_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='applied_coupon',
            field=models.BooleanField(default=False),
        ),
    ]
