# Generated by Django 5.0.6 on 2024-06-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Order Placed', 'Order Placed'), ('Order Confirmed', 'Order Confirmed'), ('Payment Processed', 'Payment Processed'), ('Order Processed', 'Order Processed'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Returned to Sender', 'Returned to Sender'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded'), ('On Hold', 'On Hold')], default='Order Placed', max_length=255, null=True),
        ),
    ]
