# Generated by Django 4.2 on 2024-04-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(models.F('title'), models.F('parent_category'), name='unique_category'),
        ),
    ]
