# Generated by Django 4.2 on 2024-04-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_is_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_visible',
        ),
        migrations.AddField(
            model_name='category',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
