# Generated by Django 4.2 on 2024-05-01 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_created_at_product_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
