# Generated by Django 4.2 on 2024-05-01 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 11, 27, 29, 443348, tzinfo=datetime.timezone.utc), verbose_name='created at'),
        ),
    ]
